# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('transport_company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=20)),
                ('orientation', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Stop'),
        ),
    ]
