# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171204_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='tipo',
            field=models.CharField(choices=[('S', 'Subida'), ('B', 'Bajada')], max_length=1),
        ),
    ]
